# Generated by Django 5.0.2 on 2024-02-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
